Repository bcgov/STRR, pull requests merged in 2024-09, with the labels that each got.

#126 Remove Use Same Address Checkbox
  strr-web/components/bcros/form-section/property/Address.vue
  strr-web/interfaces/account-i.ts
  strr-web/lang/en.json
  strr-web/nuxt.config.ts
  strr-web/package.json
  strr-web/stores/strr.ts
  strr-web/tests/unit/utils/formStateToApi.spec.ts
Labels: UI, Host

#128 Update LTSA page. Fix Terms of Service issue.
  strr-web/components/bcros/banner/banner.vue
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/application-details/[id]/ltsa/index.vue
  strr-web/pages/terms-of-service.vue
  strr-web/stores/keycloak.ts
Labels: UI, Examiner, Bugfix

#135 UI - Display Correct Ownership Type Label
  strr-web/components/bcros/form-section/review/Form.vue
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/application-details/[id]/index.vue
  strr-web/utils/common.ts
Labels: UI

#133 UI - Host Application Stepper Bug Fix & Apply Validation on Submission
  strr-web/components/bcros/form-section/principal-residence/Form.vue
  strr-web/components/bcros/form-section/property/Address.vue
  strr-web/lang/en.json
  strr-web/pages/create-account.vue
Labels: UI

#136 fix: Update UI Handling for new TOS API
  strr-web/pages/terms-of-service.vue
  strr-web/stores/account.ts
Labels: UI, Bugfix

#134 UI - Platform Application Footer
  strr-web/pages/platform-application.vue
Labels: UI, Platform Application

#142 Add Application Number to application
  strr-api/migrations/versions/20240908_0710_7a9f3c2e8b5d_.py
  strr-api/poetry.lock
  strr-api/pyproject.toml
  strr-api/src/strr_api/models/application.py
  strr-api/src/strr_api/responses/AutoApprovalRecordResponse.py
  strr-api/src/strr_api/responses/LTSARecordResponse.py
  strr-api/src/strr_api/services/application_service.py
  strr-api/tests/unit/resources/test_registration_applications.py
  strr-web/interfaces/application-i.ts
  strr-web/pages/registry-dashboard.vue
Labels: API

#143 Application Number Format - `YYYYMMDD-01234`
  strr-api/migrations/versions/20240908_0710_7a9f3c2e8b5d_.py
  strr-api/migrations/versions/20240916_1420_8b2e4d1f9c3a_.py
  strr-api/src/strr_api/models/application.py
  strr-api/src/strr_api/responses/AutoApprovalRecordResponse.py
  strr-api/src/strr_api/responses/LTSARecordResponse.py
Labels: API, Bugfix

#141 Update handling of Terms of Service
  strr-web/components/bcros/header/Menu.vue
  strr-web/components/bcros/header/MenuItem.vue
  strr-web/composables/useTermsOfService.ts
  strr-web/interfaces/terms-of-service-i.ts
  strr-web/middleware/01.setupAuth.global.ts
  strr-web/middleware/02.checkToS.global.ts
  strr-web/package.json
  strr-web/pages/account-select.vue
  strr-web/pages/create-account.vue
  strr-web/pages/platform-application.vue
  strr-web/pages/terms-of-service.vue
  strr-web/stores/account.ts
Labels: UI

#139 Add Breadcrumb Across the App
  strr-web/app.config.ts
  strr-web/components/Breadcrumb.vue
  strr-web/composables/useBreadcrumb.ts
  strr-web/enums/route-name-e.ts
  strr-web/enums/route-names-e.ts
  strr-web/interfaces/breadcrumb-i.ts
  strr-web/lang/en.json
  strr-web/layouts/default.vue
  strr-web/layouts/wide.vue
  strr-web/layouts/wideNoSpace.vue
  strr-web/page-data/breadcrumbs.ts
  strr-web/pages/application-details/[id]/auto-approval/index.vue
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/application-details/[id]/ltsa/index.vue
  strr-web/pages/listing-details/[listingId].vue
  strr-web/pages/registration-details/[id]/index.vue
  strr-web/pages/success/[id].vue
  strr-web/stores/state/strr-state-model.ts
  strr-web/stores/store.ts
  strr-web/tailwind.config.ts
  strr-web/tests/app.spec.ts
Labels: UI

#145 UI - Platform URLs and PR info on Application Details Page
  strr-web/components/bcros/form-section/property/Form.vue
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pnpm-lock.yaml
Labels: UI

#144 Add Breadcrumb Tests. Add Decline ToS Url. Update unit tests.
  strr-web/components/Breadcrumb.vue
  strr-web/components/bcros/form-section/contact-information/Form.vue
  strr-web/components/bcros/form-section/review/Form.vue
  strr-web/composables/useBcrosAuth.ts
  strr-web/composables/useBreadcrumb.ts
  strr-web/composables/useTermsOfService.ts
  strr-web/interfaces/account-i.ts
  strr-web/lang/en.json
  strr-web/middleware/02.checkToS.global.ts
  strr-web/middleware/setupAuth.global.ts
  strr-web/package.json
  strr-web/pages/platform-application.vue
  strr-web/pnpm-lock.yaml
  strr-web/tests/app.spec.ts
  strr-web/tests/mocks/mockAccounts.ts
  strr-web/tests/mocks/mockApplication.ts
  strr-web/tests/mocks/mockAxios.ts
  strr-web/tests/mocks/mockData.ts
  strr-web/tests/mocks/mockFees.ts
  strr-web/tests/mocks/mockI18n.ts
  strr-web/tests/unit/components/Breadcrumb.spec.ts
  strr-web/tests/unit/components/banner/Banner.spec.ts
  strr-web/tests/unit/components/existing-account-list/ExistingAccountList.spec.ts
  strr-web/tests/unit/components/fee-widget/FeeWidget.spec.ts
  strr-web/tests/unit/components/footer/Footer.spec.ts
  strr-web/tests/unit/components/form-section/contact-information/Form.spec.ts
  strr-web/tests/unit/components/form-section/property/Address.spec.ts
  strr-web/tests/unit/components/form-section/property/Form.spec.ts
  strr-web/tests/unit/components/form-section/review/Form.spec.ts
  strr-web/tests/unit/components/form-section/review/Item.spec.ts
  strr-web/tests/unit/components/header/MenuItem.spec.ts
  strr-web/tests/unit/components/status-card/StatusCard.spec.ts
  strr-web/tests/unit/components/stepper/Stepper.spec.ts
  strr-web/tests/unit/composables/useBcrosAuth.spec.ts
  strr-web/tests/unit/pages/platform-application.spec.ts
  strr-web/tests/unit/stores/account.spec.ts
  strr-web/tests/unit/stores/keycloak.spec.ts
  strr-web/tests/unit/utils/test-utils/mockedAccounts.json
  strr-web/vitest.config.mts
Labels: UI, Tech Debt

#147 Add Modal for Account Setup Help
  strr-web/components/common/BcrosContactInfo.vue
  strr-web/components/common/InfoModal.vue
  strr-web/composables/useBreadcrumb.ts
  strr-web/lang/en.json
  strr-web/nuxt.config.ts
  strr-web/package.json
  strr-web/pages/account-select.vue
  strr-web/pages/application-status.vue
  strr-web/pages/create-account-pre/[id].vue
  strr-web/pages/finalization.vue
  strr-web/pages/listing-details/[listingId].vue
  strr-web/pages/success/[id].vue
  strr-web/pages/success/[registrationId]/invoice/[paymentId].vue
  strr-web/tests/unit/components/BaseModal.spec.ts
Labels: UI

#146 API - Bugfix - Host Application Access
  strr-api/pyproject.toml
  strr-api/src/strr_api/models/application.py
  strr-api/src/strr_api/services/application_service.py
  strr-api/tests/unit/resources/test_registration_applications.py
Labels: API, Bugfix

#151 UI - FOIPPA Notice and STRB Contact Modal [Host Application and Dashboard]
  strr-web/components/common/InfoModal.vue
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/account-select.vue
  strr-web/pages/create-account.vue
  strr-web/pages/finalization.vue
  strr-web/pages/registry-dashboard.vue
Labels: UI

#154 UI - STRB Contact Modal [Application Status Page]
  strr-web/lang/en.json
  strr-web/pages/application-status.vue
  strr-web/pages/create-account.vue
  strr-web/pages/registry-dashboard.vue
Labels: UI
