Repository bcgov/STRR, pull requests merged in 2024-08, with the labels that each got.

#81 Use New Applications Endpoints
  strr-web/components/bcros/form-section/contact-information/Form.vue
  strr-web/composables/useApplications.ts
  strr-web/composables/useChipFlavour.ts
  strr-web/composables/useTranslation.ts
  strr-web/enums/application-status-e.ts
  strr-web/enums/registration-status-e.ts
  strr-web/interfaces/account-i.ts
  strr-web/interfaces/application-i.ts
  strr-web/interfaces/paginated-applications-i.ts
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/application-status.vue
  strr-web/pages/create-account-pre/[id].vue
  strr-web/pages/create-account.vue
  strr-web/stores/strr.ts
  strr-web/tests/unit/utils/formStateToApi.spec.ts
  strr-web/utils/formStateToApi.ts
Labels: UI

#82 Rename Translation Keys and Other Fixes
  strr-web/components/bcros/existing-accounts-list/ExistingAccountsList.vue
  strr-web/components/bcros/fee-widget/FeeWidget.vue
  strr-web/components/bcros/footer/Footer.vue
  strr-web/components/bcros/form-section/FormSection.vue
  strr-web/components/bcros/form-section/contact-information/ContactDetails.vue
  strr-web/components/bcros/form-section/contact-information/ContactInfo.vue
  strr-web/components/bcros/form-section/contact-information/CraInfo.vue
  strr-web/components/bcros/form-section/contact-information/Form.vue
  strr-web/components/bcros/form-section/contact-information/MailingAddress.vue
  strr-web/components/bcros/form-section/principal-residence/Form.vue
  strr-web/components/bcros/form-section/property/Address.vue
  strr-web/components/bcros/form-section/property/Details.vue
  strr-web/components/bcros/form-section/property/Form.vue
  strr-web/components/bcros/form-section/property/ListingDetails.vue
  strr-web/components/bcros/form-section/review/Declaration.vue
  strr-web/components/bcros/form-section/review/Form.vue
  strr-web/components/bcros/form-section/review/Subsection.vue
  strr-web/components/bcros/status-card/StatusCard.vue
  strr-web/components/bcros/stepper/StepperFooter.vue
  strr-web/components/bcros/typography/H1.vue
  strr-web/components/bcros/typography/H2.vue
  strr-web/composables/useChipFlavour.ts
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/page-data/create-account/steps.ts
  strr-web/pages/account-select.vue
  strr-web/pages/application-details/[applicationId]/auto-approval/index.vue
  strr-web/pages/application-details/[applicationId]/index.vue
  strr-web/pages/application-details/[applicationId]/ltsa/index.vue
  strr-web/pages/application-status.vue
  strr-web/pages/create-account-pre/[id].vue
  strr-web/pages/create-account.vue
  strr-web/pages/finalization.vue
  strr-web/pages/listing-details/[listingId].vue
  strr-web/pages/registry-dashboard.vue
  strr-web/pages/success/[id].vue
  strr-web/pages/success/[registrationId]/invoice/[paymentId].vue
  strr-web/pages/terms-of-service.vue
  strr-web/tests/unit/components/chip/Chip.spec.ts
  strr-web/tests/unit/components/form-section/contact-information/CraInfo.spec.ts
  strr-web/tests/unit/composables/useChipFlavour.spec.ts
Labels: UI, Tech Debt

#87 Application Count on Dashboard & UI Fixes
  .github/PULL_REQUEST_TEMPLATE.md
  strr-web/app.config.ts
  strr-web/components/bcros/banner/banner.vue
  strr-web/components/bcros/existing-accounts-list/ExistingAccountsList.vue
  strr-web/components/bcros/fee-widget/FeeWidget.vue
  strr-web/components/bcros/footer/Footer.vue
  strr-web/components/bcros/form-section/FormSection.vue
  strr-web/components/bcros/form-section/contact-information/ContactDetails.vue
  strr-web/components/bcros/form-section/contact-information/ContactInfo.vue
  strr-web/components/bcros/form-section/contact-information/CraInfo.vue
  strr-web/components/bcros/form-section/contact-information/Form.vue
  strr-web/components/bcros/form-section/contact-information/MailingAddress.vue
  strr-web/components/bcros/form-section/principal-residence/Form.vue
  strr-web/components/bcros/form-section/property/Address.vue
  strr-web/components/bcros/form-section/property/Details.vue
  strr-web/components/bcros/form-section/property/Form.vue
  strr-web/components/bcros/form-section/property/ListingDetails.vue
  strr-web/components/bcros/form-section/review/Declaration.vue
  strr-web/components/bcros/form-section/review/Form.vue
  strr-web/components/bcros/form-section/review/Subsection.vue
  strr-web/components/bcros/header/Header.vue
  strr-web/components/bcros/status-card/StatusCard.vue
  strr-web/components/bcros/stepper/Stepper.vue
  strr-web/components/bcros/stepper/StepperFooter.vue
  strr-web/composables/useChipFlavour.ts
  strr-web/enums/application-status-e.ts
  strr-web/enums/registration-status-e.ts
  strr-web/lang/en.json
  strr-web/layouts/wideGutters.vue
  strr-web/package.json
  strr-web/pages/account-select.vue
  strr-web/pages/application-details/[applicationId]/auto-approval/index.vue
  strr-web/pages/application-details/[applicationId]/index.vue
  strr-web/pages/application-details/[applicationId]/ltsa/index.vue
  strr-web/pages/application-status.vue
  strr-web/pages/create-account-pre/[id].vue
  strr-web/pages/create-account.vue
  strr-web/pages/finalization.vue
  strr-web/pages/listing-details/[listingId].vue
  strr-web/pages/registry-dashboard.vue
  strr-web/pages/success/[id].vue
  strr-web/pages/success/[registrationId]/invoice/[paymentId].vue
  strr-web/pages/terms-of-service.vue
  strr-web/tests/unit/components/chip/Chip.spec.ts
  strr-web/tests/unit/components/form-section/contact-information/ContactInfo.spec.ts
  strr-web/tests/unit/components/form-section/contact-information/CraInfo.spec.ts
  strr-web/tests/unit/composables/useChipFlavour.spec.ts
Labels: UI

#84 Backend: Scheduled Auto Approval Job
  jobs/auto-approval/.env.sample
  jobs/auto-approval/poetry.lock
  jobs/auto-approval/pyproject.toml
  jobs/auto-approval/run.sh
  jobs/auto-approval/src/auto_approval/__main__.py
  jobs/auto-approval/src/auto_approval/config.py
  jobs/auto-approval/src/auto_approval/job.py
  jobs/auto-approval/src/auto_approval/templates/certificate.html
  jobs/auto-approval/src/auto_approval/tests/test_job.py
  strr-api/src/strr_api/services/approval_service.py
  strr-api/src/strr_api/services/registration_service.py
  strr-api/tests/unit/services/test_approval.py
Labels: API

#99 Application & Registration Details pages. Filing History component. Approve & Reject Application.
  jobs/auto-approval/src/auto_approval/templates/certificate.html
  strr-api/src/strr_api/templates/certificate.html
  strr-web/components/FilingHistory.vue
  strr-web/components/bcros/banner/banner.vue
  strr-web/components/bcros/form-section/principal-residence/Form.vue
  strr-web/components/bcros/form-section/review/Form.vue
  strr-web/components/bcros/status-card/StatusCard.vue
  strr-web/composables/useApplications.ts
  strr-web/composables/useChipFlavour.ts
  strr-web/composables/useRegistrations.ts
  strr-web/enums/registration-status-e.ts
  strr-web/interfaces/account-i.ts
  strr-web/interfaces/application-history-event-i.ts
  strr-web/interfaces/application-i.ts
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/application-details/[id]/auto-approval/index.vue
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/application-details/[id]/ltsa/index.vue
  strr-web/pages/application-status.vue
  strr-web/pages/registration-details/[id]/index.vue
  strr-web/pages/success/[registrationId]/invoice/[paymentId].vue
  strr-web/stores/strr.ts
  strr-web/tests/unit/components/banner/Banner.spec.ts
  strr-web/tests/unit/components/status-card/StatusCard.spec.ts
  strr-web/tests/unit/utils/formStateToApi.spec.ts
  strr-web/tests/unit/utils/test-utils/mockedApplication.ts
  strr-web/utils/formStateToApi.ts
  strr-web/utils/format-helper.ts
Labels: UI, Host, Examiner

#105 Fix filter tabs on Examiner Dashboard
  strr-web/.eslintrc.json
  strr-web/composables/useApplications.ts
  strr-web/composables/useBcrosCanadaPost.ts
  strr-web/interfaces/paginated-applications-i.ts
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/application-status.vue
  strr-web/pages/registry-dashboard.vue
Labels: UI, Examiner

#106 Add scroll to top on Create Account steps
  strr-web/package.json
  strr-web/pages/create-account.vue
Labels: UI, Host

#104 UI - Application Details Bug Fixes
  strr-web/lang/en.json
  strr-web/pages/application-details/[id]/auto-approval/index.vue
  strr-web/pages/application-details/[id]/index.vue
Labels: bug, UI

#108 Fix Filing History dates in Registration Details
  strr-web/components/FilingHistory.vue
  strr-web/composables/useApplications.ts
  strr-web/composables/useRegistrations.ts
  strr-web/interfaces/filing-history-event-i.ts
  strr-web/interfaces/registration-history-event-i.ts
  strr-web/package.json
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/registration-details/[id]/index.vue
Labels: UI, Bugfix

#109 UI - Support New Auto Approval Record and LTSA Endpoints
  strr-api/src/strr_api/responses/AutoApprovalResponse.py
  strr-api/src/strr_api/services/application_service.py
  strr-api/src/strr_api/services/approval_service.py
  strr-web/composables/useApplications.ts
  strr-web/composables/useRegistrations.ts
  strr-web/interfaces/auto-approval-data-i.ts
  strr-web/interfaces/ltsa-data-i.ts
  strr-web/package.json
  strr-web/pages/application-details/[id]/auto-approval/index.vue
  strr-web/pages/application-details/[id]/ltsa/index.vue
Labels: UI

#110 Backend - Documents Endpoint Not Tied to Applications
  strr-api/src/strr_api/resources/__init__.py
  strr-api/src/strr_api/resources/documents.py
  strr-api/tests/postman/strr-api.postman_collection.json
Labels: API

#112 Backend - Swagger Fix in Applications document endpoints
  strr-api/src/strr_api/resources/application.py
Labels: bug, API

#113 Backend - Documents list in Registration Response
  strr-api/pyproject.toml
  strr-api/src/strr_api/responses/RegistrationResponse.py
  strr-api/src/strr_api/schemas/schemas/registration.json
Labels: API

#116 Backend - Update Registrations Document Endpoints
  strr-api/src/strr_api/resources/application.py
  strr-api/src/strr_api/resources/registrations.py
  strr-api/src/strr_api/services/document_service.py
  strr-api/tests/postman/strr-api.postman_collection.json
  strr-api/tests/unit/resources/test_registrations.py
  strr-web/composables/useRegistrations.ts
Labels: API

#114 Improve Page Loading
  strr-web/components/bcros/form-section/contact-information/Form.vue
  strr-web/enums/session-storage-e.ts
  strr-web/interfaces/account-i.ts
  strr-web/package.json
  strr-web/stores/account.ts
  strr-web/tests/unit/utils/test-utils/mockedData.ts
Labels: UI

#118 Upload and Download Supporting Documents
  strr-web/composables/useApplications.ts
  strr-web/composables/useRegistrations.ts
  strr-web/interfaces/account-i.ts
  strr-web/interfaces/application-i.ts
  strr-web/interfaces/document-upload-i.ts
  strr-web/interfaces/registration-i.ts
  strr-web/package.json
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/registration-details/[id]/index.vue
Labels: UI, Host, Examiner

#120 Platform Application Page & Stepper
  strr-web/components/bcros/stepper/Stepper.vue
  strr-web/interfaces/status-chip-flavours-i.ts
  strr-web/lang/en.json
  strr-web/layouts/wide.vue
  strr-web/package.json
  strr-web/page-data/platform-application-steps.ts
  strr-web/pages/create-account.vue
  strr-web/pages/platform-application.vue
  strr-web/public/icons/aod-active.svg
  strr-web/public/icons/aod.svg
  strr-web/public/icons/domain-add-active.svg
  strr-web/public/icons/domain-add.svg
  strr-web/tests/unit/pages/platform-application.spec.ts
  strr-web/tsconfig.json
Labels: UI, Platform Application

#123 Add Fee Summary to Platform Application page
  strr-web/components/FeeWidget.vue
  strr-web/components/bcros/stepper/StepperFooter.vue
  strr-web/composables/useFees.ts
  strr-web/layouts/wide.vue
  strr-web/package.json
  strr-web/pages/create-account-pre/[id].vue
  strr-web/pages/create-account.vue
  strr-web/pages/platform-application.vue
  strr-web/tests/unit/components/fee-widget/FeeWidget.spec.ts
  strr-web/tests/unit/pages/platform-application.spec.ts
Labels: UI, Platform Application

#124 UI - Document Upload - Align with Design
  strr-web/components/bcros/form-section/principal-residence/Form.vue
  strr-web/lang/en.json
  strr-web/package.json
Labels: UI, Host
