Repository bcgov/STRR, pull requests merged in 2024-10, with the labels that each got.

#162 Updates on Property Details Step
  strr-web/app.config.ts
  strr-web/components/bcros/form-section/property/Address.vue
  strr-web/components/bcros/form-section/property/Details.vue
  strr-web/components/bcros/form-section/property/ListingDetails.vue
  strr-web/components/bcros/tooltip/index.vue
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/application-details/[id]/index.vue
Labels: UI

#164 UI - Change Contact Email Address
  strr-web/lang/en.json
Labels: UI

#160 UI - Application Status Updates
  .sonarcloud.properties
  strr-api/src/strr_api/enums/enum.py
  strr-web/components/bcros/status-card/StatusCard.vue
  strr-web/composables/useApplications.ts
  strr-web/composables/useChipFlavour.ts
  strr-web/composables/useRegistrations.ts
  strr-web/enums/application-status-e.ts
  strr-web/enums/registration-status-e.ts
  strr-web/interfaces/account-i.ts
  strr-web/interfaces/application-i.ts
  strr-web/interfaces/pagination-i.ts
  strr-web/lang/en.json
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/application-status.vue
  strr-web/pages/registration-details/[id]/index.vue
  strr-web/pages/registry-dashboard.vue
  strr-web/tests/mocks/mockApplication.ts
  strr-web/tests/mocks/mockFilingHistory.ts
  strr-web/tests/unit/components/Breadcrumb.spec.ts
  strr-web/tests/unit/components/chip/Chip.spec.ts
  strr-web/tests/unit/composables/useChipFlavour.spec.ts
  strr-web/tests/unit/pages/application-details.spec.ts
Labels: UI

#170 Add Loading Indicator. Optimize API calls.
  strr-web/app.vue
  strr-web/components/common/LoadingIndicator.vue
  strr-web/composables/useBcrosAuth.ts
  strr-web/middleware/setupAuth.global.ts
  strr-web/nuxt.config.ts
  strr-web/package.json
  strr-web/pages/application-status.vue
  strr-web/pages/create-account.vue
  strr-web/pages/registry-dashboard.vue
  strr-web/pnpm-lock.yaml
  strr-web/stores/keycloak.ts
  strr-web/tests/app.spec.ts
  strr-web/tests/unit/composables/useBcrosAuth.spec.ts
Labels: UI

#174 Backend: Replace Application ID with Application Number
  strr-api/pyproject.toml
  strr-api/src/strr_api/models/application.py
  strr-api/src/strr_api/resources/application.py
  strr-api/src/strr_api/responses/AutoApprovalRecordResponse.py
  strr-api/src/strr_api/responses/LTSARecordResponse.py
  strr-api/src/strr_api/services/application_service.py
  strr-api/tests/postman/strr-api.postman_collection.json
  strr-api/tests/postman/strr-api.postman_environment.json
  strr-api/tests/unit/resources/test_registration_applications.py
  strr-api/tests/unit/resources/test_registrations.py
Labels: API

#176 UI: Application Status Followup Fixes
  strr-web/composables/useChipFlavour.ts
  strr-web/enums/application-status-e.ts
  strr-web/lang/en.json
  strr-web/package.json
Labels: UI

#175 Host and Examiner Actions in Application
  strr-web/components/bcros/banner/banner.vue
  strr-web/composables/useRegistrations.ts
  strr-web/composables/useScreenSize.ts
  strr-web/enums/host-examiner-actions-e.ts
  strr-web/interfaces/application-i.ts
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/application-details/[id]/auto-approval/index.vue
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/application-details/[id]/ltsa/index.vue
  strr-web/pages/registration-details/[id]/index.vue
  strr-web/pnpm-lock.yaml
  strr-web/tests/mocks/mockApplication.ts
  strr-web/tests/unit/components/banner/Banner.spec.ts
  strr-web/tests/unit/composables/useBcrosAuth.spec.ts
  strr-web/tests/unit/utils/helper-functions.ts
Labels: UI, Host, Examiner

#185 Backend: Add isCertificateIssued to applicationHeader
  strr-api/src/strr_api/models/application.py
Labels: API

#183 UI: Generic Dashboard Table for Examiners
  strr-web/components/bcros/status-card/StatusCard.vue
  strr-web/composables/useDownloadCertificate.ts
  strr-web/enums/registration-type-e.ts
  strr-web/interfaces/application-i.ts
  strr-web/interfaces/examiner-dashboard-row-i.ts
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/registry-dashboard.vue
  strr-web/tests/mocks/mockApplication.ts
Labels: UI

#196 Add Business Lic Exp Date to Details pages
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/registration-details/[id]/index.vue
Labels: UI

#195 UI: Property Manager - Update Stepper
  strr-web/components/bcros/form-section/property-manager/BusinessDetails.vue
  strr-web/components/bcros/form-section/property-manager/BusinessMailingAddress.vue
  strr-web/components/bcros/form-section/property-manager/ContactDetails.vue
  strr-web/components/bcros/form-section/property-manager/ContactName.vue
  strr-web/components/bcros/form-section/property-manager/Form.vue
  strr-web/components/bcros/stepper/Stepper.vue
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/page-data/create-account/steps.ts
  strr-web/pages/create-account.vue
  strr-web/public/icons/create-account/add_property_manager.svg
  strr-web/public/icons/create-account/add_property_manager_active.svg
  strr-web/tests/unit/components/stepper/Stepper.spec.ts
  strr-web/tests/unit/pages/rental-application.spec.ts
Labels: UI, Property Manager

#204 Update Account Flow
  strr-web/components/bcros/existing-accounts-list/ExistingAccountsList.vue
  strr-web/components/bcros/footer/Footer.vue
  strr-web/components/common/LoadingIndicator.vue
  strr-web/composables/useBcrosAuth.ts
  strr-web/composables/useBcrosNavigate.ts
  strr-web/composables/useRegistrations.ts
  strr-web/composables/useTermsOfService.ts
  strr-web/enums/route-names-e.ts
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/account-select.vue
  strr-web/pages/application-status.vue
  strr-web/pages/create-account.vue
  strr-web/pages/terms-of-service.vue
  strr-web/stores/account.ts
  strr-web/tests/unit/components/footer/Footer.spec.ts
  strr-web/tests/unit/composables/useBcrosAuth.spec.ts
  strr-web/tests/unit/stores/account.spec.ts
  strr-web/utils/axios.ts
Labels: UI

#219 UI - Platform: Submit Platform Application
  strr-platform-web/app/components/form/platform/BusinessDetails.vue
  strr-platform-web/app/components/form/platform/ReviewConfirm.vue
  strr-platform-web/app/components/form/platform/review/EditCardHeader.vue
  strr-platform-web/app/interfaces/platform-api.ts
  strr-platform-web/app/pages/platform/application.vue
  strr-platform-web/app/stores/platformApplication.ts
  strr-platform-web/app/utils/platform-application.ts
  strr-platform-web/package.json
  strr-platform-web/pnpm-lock.yaml
Labels: UI

#220 23547 rest of the property details
  strr-web/components/bcros/form-section/property/Details.vue
  strr-web/components/bcros/form-section/property/Form.vue
  strr-web/enums/host-residence-e.ts
  strr-web/enums/rental-unit-space-type-e.ts
  strr-web/interfaces/account-i.ts
  strr-web/lang/en.json
  strr-web/stores/strr.ts
  strr-web/utils/formStateToApi.ts
Labels: UI

#209 UI: Property Manager Step 1 Implementation
  strr-web/components/bcros/form-section/property-manager/BusinessDetails.vue
  strr-web/components/bcros/form-section/property-manager/BusinessMailingAddress.vue
  strr-web/components/bcros/form-section/property-manager/ContactDetails.vue
  strr-web/components/bcros/form-section/property-manager/ContactName.vue
  strr-web/components/bcros/form-section/property-manager/Form.vue
  strr-web/interfaces/account-i.ts
  strr-web/interfaces/address-i.ts
  strr-web/interfaces/property-manager-i.ts
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/page-data/create-account/steps.ts
  strr-web/pages/create-account.vue
  strr-web/public/icons/create-account/account_multiple_plus.svg
  strr-web/public/icons/create-account/account_multiple_plus_active.svg
  strr-web/public/icons/create-account/home_owner.svg
  strr-web/public/icons/create-account/home_owner_active.svg
  strr-web/public/icons/create-account/text_box_check.svg
  strr-web/public/icons/create-account/text_box_check_active.svg
  strr-web/stores/strr.ts
  strr-web/tests/unit/components/form-section/property-manager/BusinessDetails.spec.ts
  strr-web/tests/unit/components/form-section/property-manager/BusinessMailingAddress.spec.ts
  strr-web/tests/unit/components/form-section/property-manager/ContactDetails.spec.ts
  strr-web/tests/unit/components/form-section/property-manager/ContactName.spec.ts
  strr-web/tests/unit/components/form-section/property-manager/Form.spec.ts
  strr-web/tests/unit/pages/rental-application.spec.ts
  strr-web/utils/formStateToApi.ts
  strr-web/utils/provinces.json
Labels: UI, Property Manager

#224 UI - Property Manager Fixes - From QA Testing
  strr-web/components/bcros/form-section/property-manager/ContactDetails.vue
  strr-web/components/bcros/form-section/property-manager/Form.vue
  strr-web/package.json
  strr-web/stores/strr.ts
Labels: UI, Property Manager

#226 Platform - UI: auth setup for e2e tests
  strr-platform-web/.env.example
  strr-platform-web/playwright.config.ts
  strr-platform-web/tests/e2e/platform.smoke.test.ts
  strr-platform-web/tests/e2e/test-utils/auth-setup.ts
Labels: UI

#227 UI - Validation Updates - QA Feedback
  strr-web/components/bcros/form-section/contact-information/ContactDetails.vue
  strr-web/components/bcros/form-section/property-manager/BusinessDetails.vue
  strr-web/components/bcros/form-section/property-manager/ContactDetails.vue
  strr-web/components/bcros/form-section/property-manager/ContactName.vue
  strr-web/components/bcros/form-section/property-manager/Form.vue
  strr-web/package.json
  strr-web/stores/strr.ts
  strr-web/tests/unit/components/form-section/property-manager/BusinessDetails.spec.ts
  strr-web/tests/unit/components/form-section/property-manager/BusinessMailingAddress.spec.ts
  strr-web/tests/unit/components/form-section/property-manager/ContactDetails.spec.ts
  strr-web/tests/unit/components/form-section/property-manager/ContactName.spec.ts
  strr-web/tests/unit/components/form-section/property-manager/Form.spec.ts
Labels: UI, Property Manager

#210 Property Manager - Review and Confirm, App & Reg Details pages
  strr-web/components/FilingHistory.vue
  strr-web/components/bcros/form-section/contact-information/Form.vue
  strr-web/components/bcros/form-section/property-manager/Form.vue
  strr-web/components/bcros/form-section/property-manager/SummaryView.vue
  strr-web/components/bcros/form-section/property/Details.vue
  strr-web/components/bcros/form-section/property/Form.vue
  strr-web/components/bcros/form-section/review/Form.vue
  strr-web/components/bcros/form-section/review/Subsection.vue
  strr-web/composables/useApplications.ts
  strr-web/interfaces/account-i.ts
  strr-web/interfaces/application-i.ts
  strr-web/interfaces/registration-i.ts
  strr-web/lang/en.json
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/create-account.vue
  strr-web/pages/finalization.vue
  strr-web/pages/registration-details/[id]/index.vue
  strr-web/stores/strr.ts
  strr-web/tests/mocks/mockApplication.ts
  strr-web/tests/mocks/mockPropertyManager.ts
  strr-web/tests/unit/components/form-section/property/Form.spec.ts
  strr-web/tests/unit/components/form-section/review/Subsection.spec.ts
  strr-web/tests/unit/pages/rental-application.spec.ts
  strr-web/tests/unit/utils/formStateToApi.spec.ts
  strr-web/utils/format-helper.ts
Labels: UI, Property Manager

#222 UI: Examiner Dashboard UI Changes
  strr-web/composables/useApplications.ts
  strr-web/composables/useDownloadReceipt.ts
  strr-web/enums/listing-size-e.ts
  strr-web/enums/registration-type-e.ts
  strr-web/interfaces/application-i.ts
  strr-web/interfaces/examiner-dashboard-row-i.ts
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/application-details/[id]/auto-approval/index.vue
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/application-details/[id]/ltsa/index.vue
  strr-web/pages/registry-dashboard.vue
  strr-web/tests/mocks/mockApplication.ts
Labels: UI

#236 Update Account Flow
  strr-web/composables/useBcrosAuth.ts
  strr-web/package.json
  strr-web/stores/account.ts
  strr-web/stores/keycloak.ts
Labels: UI

#231 24009 add property detail to review confirm page
  strr-web/components/bcros/form-section/property/Details.vue
  strr-web/components/bcros/form-section/property/Form.vue
  strr-web/components/bcros/form-section/review/Form.vue
  strr-web/composables/useApplications.ts
  strr-web/interfaces/account-i.ts
  strr-web/interfaces/application-i.ts
  strr-web/interfaces/registration-i.ts
  strr-web/lang/en.json
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/create-account-pre/[id].vue
  strr-web/pages/create-account.vue
  strr-web/pages/registration-details/[id]/index.vue
  strr-web/stores/strr.ts
  strr-web/tests/unit/pages/rental-application.spec.ts
  strr-web/utils/formStateToApi.ts
Labels: UI, Property Manager

#238 Platform - UI: A11y Updates
  strr-platform-web/app/components/connect/form/address/Index.vue
  strr-platform-web/app/components/connect/form/field/Group.vue
  strr-platform-web/app/components/connect/form/field/Index.vue
  strr-platform-web/app/components/connect/form/phoneNumber/CountryCode.vue
  strr-platform-web/app/components/connect/form/phoneNumber/Index.vue
  strr-platform-web/app/components/form/common/Contact.vue
  strr-platform-web/app/components/form/platform/BusinessDetails.vue
  strr-platform-web/app/components/form/platform/ContactInfo.vue
  strr-platform-web/app/components/form/platform/Details.vue
  strr-platform-web/app/components/form/platform/ReviewConfirm.vue
  strr-platform-web/app/locales/en-CA.ts
  strr-platform-web/app/utils/connect-validation/index.ts
Labels: enhancement, UI

#246 Platform - UI: Review section errors
  strr-platform-web/app/components/connect/Stepper.vue
  strr-platform-web/app/components/form/common/Review/Row.vue
  strr-platform-web/app/components/form/common/Review/Section.vue
  strr-platform-web/app/components/form/platform/ReviewConfirm.vue
  strr-platform-web/app/composables/useStrrModals.ts
  strr-platform-web/app/locales/en-CA.ts
  strr-platform-web/app/pages/platform/application.vue
Labels: enhancement, UI, Platform Application

#249 API - Get Account-Id from Request - `/<application_number>/payment/receipt`
  strr-api/src/strr_api/resources/application.py
Labels: API

#248 Platform - UI: Login page
  strr-platform-web/app/app.config.ts
  strr-platform-web/app/assets/styles/layout.css
  strr-platform-web/app/locales/en-CA.ts
  strr-platform-web/app/middleware/auth.ts
  strr-platform-web/app/middleware/login-page.ts
  strr-platform-web/app/pages/auth/login.vue
  strr-platform-web/app/pages/platform/application.vue
  strr-platform-web/app/pages/platform/dashboard.vue
  strr-platform-web/devops/vaults.env
  strr-platform-web/public/img/BCReg_Generic_Login_image.jpg
Labels: enhancement, UI, Platform Application

#250 Host UI - Host Receipt Download Link
  strr-web/components/bcros/buttons/Primary.vue
  strr-web/components/bcros/status-card/StatusCard.vue
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/registration-details/[id]/index.vue
  strr-web/tests/unit/components/status-card/StatusCard.spec.ts
Labels: UI

#239 Add Host Authorization checkbox for Property Managers
  strr-web/components/bcros/form-section/property-manager/Form.vue
  strr-web/components/bcros/form-section/property/Form.vue
  strr-web/components/bcros/form-section/review/Form.vue
  strr-web/interfaces/account-i.ts
  strr-web/lang/en.json
  strr-web/pages/create-account.vue
  strr-web/stores/strr.ts
  strr-web/tests/unit/pages/rental-application.spec.ts
  strr-web/utils/format-helper.ts
Labels: UI, Property Manager

#251 Host UI - Application Submit Button - Loading Animation
  strr-web/components/bcros/stepper/StepperFooter.vue
  strr-web/package.json
  strr-web/pages/create-account.vue
  strr-web/tests/unit/components/stepper/StepperFooter.spec.ts
Labels: UI, Bugfix

#254 Host UI - Only Allow PDF Document Upload
  strr-web/components/bcros/form-section/principal-residence/Form.vue
  strr-web/lang/en.json
  strr-web/package.json
Labels: UI
