Repository bcgov/STRR, pull requests merged in 2024-11, with the labels that each got.

#253 23547 uxa suggested changes
  strr-web/components/bcros/form-section/property/Details.vue
  strr-web/components/bcros/form-section/property/Form.vue
  strr-web/components/bcros/form-section/review/Form.vue
  strr-web/lang/en.json
  strr-web/pages/application-details/[id]/index.vue
  strr-web/tests/unit/components/form-section/property/Details.spec.ts
  strr-web/tests/unit/pages/rental-application.spec.ts
Labels: UI

#256 Platform - UI: Choose account page
  strr-platform-web/app/composables/useStrrModals.ts
  strr-platform-web/app/locales/en-CA.ts
  strr-platform-web/app/middleware/require-premium-account.ts
  strr-platform-web/app/pages/auth/account/choose-existing.vue
  strr-platform-web/app/pages/platform/application.vue
  strr-platform-web/app/pages/platform/dashboard.vue
Labels: UI, Platform Application

#261 23875 pid to examiner registration detail view
  strr-web/components/bcros/form-section/property/Details.vue
  strr-web/components/bcros/form-section/property/Form.vue
  strr-web/lang/en.json
  strr-web/pages/registration-details/[id]/index.vue
Labels: UI

#267 Submit Application as a Business
  strr-web/app.config.ts
  strr-web/components/bcros/form-section/BusinessDetails.vue
  strr-web/components/bcros/form-section/ContactDetails.vue
  strr-web/components/bcros/form-section/ContactName.vue
  strr-web/components/bcros/form-section/contact-information/ContactDetails.vue
  strr-web/components/bcros/form-section/contact-information/ContactInfo.vue
  strr-web/components/bcros/form-section/contact-information/CraInfo.vue
  strr-web/components/bcros/form-section/contact-information/Form.vue
  strr-web/components/bcros/form-section/property-manager/BusinessMailingAddress.vue
  strr-web/components/bcros/form-section/property-manager/Form.vue
  strr-web/components/bcros/form-section/property/Details.vue
  strr-web/components/bcros/form-section/property/ListingDetails.vue
  strr-web/components/bcros/form-section/review/Form.vue
  strr-web/components/bcros/form-section/review/Subsection.vue
  strr-web/composables/useApplications.ts
  strr-web/composables/useBcrosAuth.ts
  strr-web/enums/host-contact-type-e.ts
  strr-web/interfaces/account-i.ts
  strr-web/lang/en.json
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/create-account-pre/[id].vue
  strr-web/pages/create-account.vue
  strr-web/pages/finalization.vue
  strr-web/stores/strr.ts
  strr-web/tests/mocks/mockApplication.ts
  strr-web/tests/unit/components/form-section/ContactDetails.spec.ts
  strr-web/tests/unit/components/form-section/contact-information/ContactDetails.spec.ts
  strr-web/tests/unit/components/form-section/contact-information/ContactInfo.spec.ts
  strr-web/tests/unit/components/form-section/contact-information/Form.spec.ts
  strr-web/tests/unit/components/form-section/property-manager/BusinessDetails.spec.ts
  strr-web/tests/unit/components/form-section/property-manager/ContactDetails.spec.ts
  strr-web/tests/unit/components/form-section/property-manager/ContactName.spec.ts
  strr-web/tests/unit/components/form-section/property/Details.spec.ts
  strr-web/tests/unit/pages/rental-application.spec.ts
  strr-web/tests/unit/pages/validate-forms.spec.ts
  strr-web/tests/unit/utils/formStateToApi.spec.ts
  strr-web/utils/formStateToApi.ts
Labels: UI

#270 Fix Property Details and Review pages
  strr-web/components/bcros/form-section/property-manager/SummaryView.vue
  strr-web/components/bcros/form-section/property/Details.vue
  strr-web/components/bcros/form-section/property/Form.vue
  strr-web/components/bcros/form-section/property/SummaryView.vue
  strr-web/components/bcros/form-section/review/Form.vue
  strr-web/interfaces/account-i.ts
  strr-web/interfaces/property-details-i.ts
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/application-status.vue
  strr-web/pages/registration-details/[id]/index.vue
  strr-web/stores/strr.ts
  strr-web/tests/unit/pages/rental-application.spec.ts
  strr-web/utils/format-helper.ts
Labels: UI

#282 Account Flow Updates. Breadcrumb Fix.
  strr-web/components/bcros/footer/Footer.vue
  strr-web/components/bcros/form-section/principal-residence/Form.vue
  strr-web/composables/useBcrosAuth.ts
  strr-web/package.json
  strr-web/page-data/breadcrumbs.ts
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/registration-details/[id]/index.vue
  strr-web/stores/keycloak.ts
Labels: UI, Bugfix

#283 UI - Payment Fail Banner and ApplicationDetails Unit Test
  strr-web/lang/en.json
  strr-web/pages/application-details/[id]/index.vue
  strr-web/tests/mocks/mockApplication.ts
  strr-web/tests/unit/pages/application-details.spec.ts
Labels: UI, Tech Debt

#288 UI - Examiner Dashboard - PropertyManager Application Type Fix
  strr-api/src/strr_api/requests/RegistrationRequest.py
  strr-api/src/strr_api/schemas/schemas/host-registration.json
  strr-api/tests/mocks/json/host_registration_property_manager.json
  strr-web/interfaces/property-manager-i.ts
  strr-web/package.json
  strr-web/pages/registry-dashboard.vue
  strr-web/stores/strr.ts
  strr-web/utils/formStateToApi.ts
Labels: UI, Property Manager

#278 Cleanup Tech Debt
  strr-web/composables/useApplications.ts
  strr-web/pages/create-account-pre/[id].vue
  strr-web/pages/create-account.vue
  strr-web/stores/strr.ts
Labels: UI, Host, Tech Debt, Examiner

#290 Fix Account Flow for Host
  strr-web/composables/useBcrosAuth.ts
  strr-web/composables/useBcrosNavigate.ts
  strr-web/composables/useRegistrations.ts
  strr-web/composables/useTermsOfService.ts
  strr-web/lang/en.json
  strr-web/middleware/setupAuth.global.ts
  strr-web/package.json
  strr-web/pages/account-select.vue
  strr-web/pages/application-status.vue
  strr-web/pages/create-account.vue
  strr-web/pages/registry-dashboard.vue
  strr-web/pages/success/[id].vue
  strr-web/pages/success/[registrationId]/invoice/[paymentId].vue
  strr-web/pages/terms-of-service.vue
  strr-web/stores/account.ts
Labels: UI

#294 Allow to Navigate to Success Submission page
  strr-web/middleware/setupAuth.global.ts
  strr-web/package.json
  strr-web/stores/keycloak.ts
Labels: UI, Bugfix

#305 UI - Document Upload Fixes, Listing Url and Single Checkbox
  strr-web/components/bcros/form-section/principal-residence/Form.vue
  strr-web/components/bcros/form-section/property/Form.vue
  strr-web/components/bcros/form-section/property/SummaryView.vue
  strr-web/components/bcros/form-section/review/Form.vue
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/create-account.vue
  strr-web/pages/registration-details/[id]/index.vue
  strr-web/stores/strr.ts
  strr-web/tests/unit/pages/rental-application.spec.ts
Labels: UI

#311 UI - Document Required Learn More Link Update
  strr-web/components/bcros/form-section/principal-residence/Form.vue
  strr-web/components/bcros/form-section/review/Form.vue
  strr-web/package.json
Labels: UI

#306 Update Validations for Host Rental Application
  strr-web/components/bcros/form-section/BusinessDetails.vue
  strr-web/components/bcros/form-section/ContactDetails.vue
  strr-web/components/bcros/form-section/ContactName.vue
  strr-web/components/bcros/form-section/contact-information/ContactInfo.vue
  strr-web/components/bcros/form-section/contact-information/CraInfo.vue
  strr-web/components/bcros/form-section/contact-information/Form.vue
  strr-web/components/bcros/form-section/contact-information/MailingAddress.vue
  strr-web/components/bcros/form-section/principal-residence/Form.vue
  strr-web/components/bcros/form-section/property-manager/BusinessMailingAddress.vue
  strr-web/components/bcros/form-section/property-manager/Form.vue
  strr-web/components/bcros/form-section/property/Address.vue
  strr-web/components/bcros/form-section/property/Details.vue
  strr-web/components/bcros/form-section/property/Form.vue
  strr-web/components/bcros/form-section/property/SummaryView.vue
  strr-web/interfaces/account-i.ts
  strr-web/interfaces/property-details-i.ts
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/create-account.vue
  strr-web/stores/strr.ts
  strr-web/tests/unit/components/form-section/ContactDetails.spec.ts
  strr-web/tests/unit/components/form-section/contact-information/ContactInfo.spec.ts
  strr-web/tests/unit/components/form-section/contact-information/Form.spec.ts
  strr-web/tests/unit/components/form-section/property-manager/BusinessMailingAddress.spec.ts
  strr-web/tests/unit/components/form-section/property-manager/ContactDetails.spec.ts
  strr-web/tests/unit/components/form-section/property-manager/ContactName.spec.ts
  strr-web/tests/unit/components/form-section/property/Address.spec.ts
  strr-web/tests/unit/components/form-section/property/Details.spec.ts
  strr-web/tests/unit/components/header/Header.spec.ts
  strr-web/tests/unit/pages/validate-forms.spec.ts
  strr-web/utils/formStateToApi.ts
Labels: UI, Host, Bugfix

#319 Update Host Information step as per Figma
  strr-web/components/bcros/form-section/contact-information/Form.vue
  strr-web/components/bcros/form-section/review/Form.vue
  strr-web/components/bcros/form-section/review/Subsection.vue
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/tests/mocks/mockApplication.ts
  strr-web/tests/unit/pages/rental-application.spec.ts
Labels: UI, Host

#322 Update Text on Submission Page
  strr-web/lang/en.json
  strr-web/package.json
  strr-web/pages/listing-details/[listingId].vue
  strr-web/pages/success/[id].vue
  strr-web/pages/success/[registrationId]/invoice/[paymentId].vue
Labels: UI

#339 Examiner Updates
  strr-web/enums/route-names-e.ts
  strr-web/package.json
  strr-web/pages/application-details/[id]/auto-approval/index.vue
  strr-web/pages/application-details/[id]/index.vue
  strr-web/pages/application-details/[id]/ltsa/index.vue
  strr-web/pages/registration-details/[id]/index.vue
  strr-web/pages/staff-str-dashboard.vue
  strr-web/tests/unit/pages/application-details.spec.ts
Labels: UI, Examiner
